// // /* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
// //    Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

// //    Detected compiler: GNU C++
// // */

// // #include <defs.h>


// // //-------------------------------------------------------------------------
// // // Function declarations

// // __int64 (**init_proc())(void);
// // void sub_1020();
// // void sub_1030();
// // void sub_1040();
// // void sub_1050();
// // void sub_1060();
// // void sub_1070();
// // void sub_1080();
// // // int _cxa_finalize(void *);
// // // int putchar(int c);
// // // int puts(const char *s);
// // // size_t strlen(const char *s);
// // // int printf(const char *format, ...);
// // // __int64 __isoc99_scanf(const char *, ...); weak
// // void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
// // char *sub_1130();
// // __int64 sub_1160();
// // char *sub_11A0();
// // __int64 sub_11E0();
// // unsigned __int64 __fastcall sub_11E9(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5);
// // void term_proc();
// // // int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// // // int __cxa_finalize(void *);
// // // __int64 _gmon_start__(void); weak

// // //-------------------------------------------------------------------------
// // // Data declarations

// // _UNKNOWN main;
// // char aU[304] = "_______________________________\n|_U_    |    ___|___    |    ___|\n|    ___    |       |   ____    |\n|___|   |_______|___________|   |\n|           |       |   ________|\n#.####..##.#.##.....#.##...####..\n..###.#.####.#..#.#.#..#.. .###.#\n.#.###.#.#.#..#.#.....##.#.....#.\n...##...###.#..##..###.#.#######\n"; // weak
// // _UNKNOWN unk_21E0; // weak
// // void *off_4008 = &off_4008; // idb
// // char byte_4010; // weak


// // //----- (0000000000001000) ----------------------------------------------------
// // __int64 (**init_proc())(void)
// // {
// //   __int64 (**result)(void); // rax

// //   result = &_gmon_start__;
// //   if ( &_gmon_start__ )
// //     return (__int64 (**)(void))_gmon_start__();
// //   return result;
// // }
// // // 4060: using guessed type __int64 _gmon_start__(void);

// // //----- (0000000000001020) ----------------------------------------------------
// // void sub_1020()
// // {
// //   JUMPOUT(0);
// // }
// // // 1026: control flows out of bounds to 0

// // //----- (0000000000001030) ----------------------------------------------------
// // void sub_1030()
// // {
// //   sub_1020();
// // }

// // //----- (0000000000001040) ----------------------------------------------------
// // void sub_1040()
// // {
// //   sub_1020();
// // }

// // //----- (0000000000001050) ----------------------------------------------------
// // void sub_1050()
// // {
// //   sub_1020();
// // }

// // //----- (0000000000001060) ----------------------------------------------------
// // void sub_1060()
// // {
// //   sub_1020();
// // }

// // //----- (0000000000001070) ----------------------------------------------------
// // void sub_1070()
// // {
// //   sub_1020();
// // }

// // //----- (0000000000001080) ----------------------------------------------------
// // void sub_1080()
// // {
// //   sub_1020();
// // }

// // //----- (0000000000001100) ----------------------------------------------------
// // // positive sp value has been detected, the output may be wrong!
// // void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
// // {
// //   __int64 v3; // rax
// //   int v4; // esi
// //   __int64 v5; // [rsp-8h] [rbp-8h] BYREF
// //   char *retaddr; // [rsp+0h] [rbp+0h] BYREF

// //   v4 = v5;
// //   v5 = v3;
// //   _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, 0, 0, a3, &v5);
// //   __halt();
// // }
// // // 110A: positive sp value 8 has been found
// // // 1111: variable 'v3' is possibly undefined

// // //----- (0000000000001130) ----------------------------------------------------
// // char *sub_1130()
// // {
// //   return &byte_4010;
// // }
// // // 4010: using guessed type char byte_4010;

// // //----- (0000000000001160) ----------------------------------------------------
// // __int64 sub_1160()
// // {
// //   return 0;
// // }

// // //----- (00000000000011A0) ----------------------------------------------------
// // char *sub_11A0()
// // {
// //   char *result; // rax

// //   if ( !byte_4010 )
// //   {
// //     if ( &__cxa_finalize )
// //       _cxa_finalize(off_4008);
// //     result = sub_1130();
// //     byte_4010 = 1;
// //   }
// //   return result;
// // }
// // // 4010: using guessed type char byte_4010;

// // //----- (00000000000011E0) ----------------------------------------------------
// // // attributes: thunk
// // __int64 sub_11E0()
// // {
// //   return sub_1160();
// // }

// // //----- (00000000000011E9) ----------------------------------------------------
// // unsigned __int64 __fastcall sub_11E9(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5)
// // {
// //   __int64 v5; // kr00_8
// //   __int64 v6; // kr08_8
// //   char v8; // [rsp+3Bh] [rbp-225h]
// //   char v9; // [rsp+3Bh] [rbp-225h]
// //   int i; // [rsp+3Ch] [rbp-224h]
// //   int j; // [rsp+3Ch] [rbp-224h]
// //   int v12; // [rsp+3Ch] [rbp-224h]
// //   int v13; // [rsp+40h] [rbp-220h]
// //   int v14; // [rsp+40h] [rbp-220h]
// //   __int64 k; // [rsp+48h] [rbp-218h]
// //   _BYTE v16[520]; // [rsp+50h] [rbp-210h]
// //   unsigned __int64 v17; // [rsp+258h] [rbp-8h]

// //   v17 = __readfsqword(0x28u);
// //   for ( i = 0; i <= 255; ++i )
// //   {
// //     v16[i + 256] = i;
// //     v16[i] = *(_BYTE *)(i % a4 + a3);
// //   }
// //   v13 = 0;
// //   for ( j = 0; j <= 255; ++j )
// //   {
// //     v5 = v13 + (unsigned __int8)v16[j + 256] + (unsigned __int8)v16[j];
// //     v13 = (unsigned __int8)(HIBYTE(v5) + v13 + v16[j + 256] + v16[j]) - HIBYTE(HIDWORD(v5));
// //     v8 = v16[j + 256];
// //     v16[j + 256] = v16[v13 + 256];
// //     v16[v13 + 256] = v8;
// //   }
// //   v12 = 0;
// //   v14 = 0;
// //   for ( k = 0; k < a2; ++k )
// //   {
// //     v12 = (v12 + 1) % 256;
// //     v6 = (unsigned __int8)v16[v12 + 256] + v14;
// //     v14 = (unsigned __int8)(HIBYTE(v6) + v16[v12 + 256] + v14) - HIBYTE(HIDWORD(v6));
// //     v9 = v16[v12 + 256];
// //     v16[v12 + 256] = v16[v14 + 256];
// //     v16[v14 + 256] = v9;
// //     *(_BYTE *)(k + a5) = *(_BYTE *)(k + a1) ^ v16[(unsigned __int8)(v16[v12 + 256] + v16[v14 + 256]) + 256];
// //   }
// //   return v17 - __readfsqword(0x28u);
// // }

// // //----- (00000000000014B9) ----------------------------------------------------
// // __int64 __fastcall main(int a1, char **a2, char **a3)
// // {
// //   size_t v4; // rbx
// //   size_t v5; // rsi
// //   char v6; // [rsp+Fh] [rbp-501h]
// //   int v7; // [rsp+10h] [rbp-500h]
// //   int i; // [rsp+14h] [rbp-4FCh]
// //   int j; // [rsp+18h] [rbp-4F8h]
// //   int v10; // [rsp+1Ch] [rbp-4F4h]
// //   int k; // [rsp+20h] [rbp-4F0h]
// //   int v12; // [rsp+24h] [rbp-4ECh]
// //   _DWORD v13[256]; // [rsp+30h] [rbp-4E0h] BYREF
// //   char v14[8]; // [rsp+430h] [rbp-E0h] BYREF
// //   __int64 v15; // [rsp+438h] [rbp-D8h]
// //   unsigned __int64 v16; // [rsp+440h] [rbp-D0h]
// //   __int64 v17; // [rsp+448h] [rbp-C8h]
// //   __int64 v18; // [rsp+450h] [rbp-C0h]
// //   char v19[48]; // [rsp+460h] [rbp-B0h] BYREF
// //   char s[104]; // [rsp+490h] [rbp-80h] BYREF
// //   unsigned __int64 v21; // [rsp+4F8h] [rbp-18h]

// //   v21 = __readfsqword(0x28u);
// //   *(_QWORD *)v14 = 0xE8482736A5706406LL;
// //   v15 = 0x6A8A56B322AE3F12LL;
// //   v16 = 0xC348522ABB1A2CB4LL;
// //   v17 = 0x2F3FEB54C9C7994LL;
// //   v18 = 11531973;
// //   qmemcpy(v13, &unk_21E0, sizeof(v13));
// //   v7 = 0;
// //   for ( i = 0; aU[i]; ++i )
// //     putchar(aU[i]);
// //   printf("\nEnter the moves [a/w/s/d]: ");
// //   __isoc99_scanf("%s", s);
// //   if ( strlen(s) == 39 )
// //   {
// //     for ( j = 0; j < strlen(s); ++j )
// //     {
// //       v6 = s[j];
// //       v12 = 4 * v7;
// //       v10 = 0;
// //       if ( v6 == 100 && v13[v12 + 3] == 1 && v7 % 8 != 7 )
// //       {
// //         ++v7;
// //         v10 = 1;
// //       }
// //       else if ( v6 == 97 && v13[v12] == 1 && (v7 & 7) != 0 )
// //       {
// //         --v7;
// //         v10 = 1;
// //       }
// //       else if ( v6 == 115 && v13[v12 + 2] == 1 && v7 <= 55 )
// //       {
// //         v7 += 8;
// //         v10 = 1;
// //       }
// //       else if ( v6 == 119 && v13[v12 + 1] == 1 && v7 > 7 )
// //       {
// //         v7 -= 8;
// //         v10 = 1;
// //       }
// //       if ( !v10 )
// //       {
// //         puts("you've reached a dead end");
// //         return 1;
// //       }
// //     }
// //     if ( v7 == 40 )
// //     {
// //       v4 = strlen(s);
// //       v5 = strlen(v14);
// //       sub_11E9((__int64)v14, v5, (__int64)s, v4, (__int64)v19);
// //       printf("You're out, here's your flag: ");
// //       for ( k = 0; k < strlen(v14); ++k )
// //         putchar((unsigned __int8)v19[k]);
// //       putchar(10);
// //     }
// //     else
// //     {
// //       puts("you've come the wrong way...");
// //     }
// //     return 0;
// //   }
// //   else
// //   {
// //     puts("you're not there yet");
// //     return 1;
// //   }
// // }
// // // 10F0: using guessed type __int64 __isoc99_scanf(const char *, ...);

// // //----- (000000000000186C) ----------------------------------------------------
// // void term_proc()
// // {
// //   ;
// // }

// // // nfuncs=32 queued=16 decompiled=16 lumina nreq=0 worse=0 better=0
// // // ALL OK, 16 function(s) have been successfully decompiled


// #include <stdio.h>
// #include <string.h>
// #include <stdint.h>

// // Stubbed external functions (assumed from decompilation)
// void _cxa_finalize(void *d) { /* Placeholder */ }
// void _libc_start_main(int (*main)(int, char **, char **), int argc, char **argv, 
//                       void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), 
//                       void *stack_end) { main(argc, argv, NULL); }
// void __halt(void) { while (1); }

// // Global data
// char aU[304] = "_______________________________\n|_U_    |    ___|___    |    ___|\n|    ___    |       |   ____    |\n|___|   |_______|___________|   |\n|           |       |   ________|\n#.####..##.#.##.....#.##...####..\n..###.#.####.#..#.#.#..#.. .###.#\n.#.###.#.#.#..#.#.....##.#.....#.\n...##...###.#..##..###.#.#######\n";
// char byte_4010 = 0;
// void *off_4008 = &off_4008;

// // Placeholder for undefined external data
// uint32_t unk_21E0[256] = {0}; // Assuming a 256-element array for maze data

// // Initialization stub
// __int64 (**init_proc())(void) {
//     return NULL; // Simplified, assuming no gmon_start needed
// }

// // Start function (fixed)
// void __attribute__((noreturn)) start(__int64 a1, __int64 a2, void (*a3)(void)) {
//     __int64 stack_end = 0; // Define v3 equivalent
//     char *argv[2] = {NULL, NULL}; // Minimal argv
//     _libc_start_main(main, a2, argv, NULL, NULL, a3, &stack_end);
//     __halt();
// }

// // RC4-like encryption function
// unsigned __int64 sub_11E9(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5) {
//     uint8_t v16[512];
//     int i, j, v12, v13, v14;
//     __int64 k;
//     unsigned __int64 v17 = 0; // Stack canary placeholder

//     for (i = 0; i <= 255; ++i) {
//         v16[i + 256] = i;
//         v16[i] = *(((uint8_t *)a3) + (i % a4));
//     }
//     v13 = 0;
//     for (j = 0; j <= 255; ++j) {
//         v13 = (v13 + v16[j + 256] + v16[j]) % 256;
//         uint8_t temp = v16[j + 256];
//         v16[j + 256] = v16[v13 + 256];
//         v16[v13 + 256] = temp;
//     }
//     v12 = 0;
//     v14 = 0;
//     for (k = 0; k < a2; ++k) {
//         v12 = (v12 + 1) % 256;
//         v14 = (v14 + v16[v12 + 256]) % 256;
//         uint8_t temp = v16[v12 + 256];
//         v16[v12 + 256] = v16[v14 + 256];
//         v16[v14 + 256] = temp;
//         ((uint8_t *)a5)[k] = ((uint8_t *)a1)[k] ^ v16[(v16[v12 + 256] + v16[v14 + 256]) % 256 + 256];
//     }
//     return v17; // Simplified, no stack check
// }

// // Main function (core logic preserved)
// int main(int argc, char **argv, char **envp) {
//     size_t v4, v5;
//     char v6;
//     int v7 = 0, i, j, v10, v12;
//     uint32_t v13[256];
//     char v14[8] = {0x06, 0x64, 0x70, 0xA5, 0x36, 0x27, 0x48, 0xE8};
//     char v19[48] = {0};
//     char s[104];

//     memcpy(v13, unk_21E0, sizeof(v13));
//     for (i = 0; aU[i]; ++i)
//         putchar(aU[i]);
//     printf("\nEnter the moves [a/w/s/d]: ");
//     scanf("%103s", s); // Limit input to avoid buffer overflow

//     if (strlen(s) == 39) {
//         for (j = 0; j < strlen(s); ++j) {
//             v6 = s[j];
//             v12 = 4 * v7;
//             v10 = 0;
//             if (v6 == 'd' && v13[v12 + 3] == 1 && v7 % 8 != 7) {
//                 ++v7;
//                 v10 = 1;
//             } else if (v6 == 'a' && v13[v12] == 1 && (v7 & 7) != 0) {
//                 --v7;
//                 v10 = 1;
//             } else if (v6 == 's' && v13[v12 + 2] == 1 && v7 <= 55) {
//                 v7 += 8;
//                 v10 = 1;
//             } else if (v6 == 'w' && v13[v12 + 1] == 1 && v7 > 7) {
//                 v7 -= 8;
//                 v10 = 1;
//             }
//             if (!v10) {
//                 puts("you've reached a dead end");
//                 return 1;
//             }
//         }
//         if (v7 == 40) {
//             v4 = strlen(s);
//             v5 = strlen(v14);
//             sub_11E9((int64_t)v14, v5, (int64_t)s, v4, (int64_t)v19);
//             printf("You're out, here's your flag: ");
//             for (i = 0; i < strlen(v14); ++i)
//                 putchar((unsigned char)v19[i]);
//             putchar('\n');
//         } else {
//             puts("you've come the wrong way...");
//         }
//         return 0;
//     } else {
//         puts("you're not there yet");
//         return 1;
//     }
// }

// // Termination stub
// void term_proc() {}


#include <stdio.h>
#include <string.h>
#include <stdint.h>

// Forward declaration of main
int main(int argc, char **argv, char **envp);

// Stubbed external functions
void _cxa_finalize(void *d) { /* Placeholder */ }
void _libc_start_main(int (*main)(int, char **, char **), int argc, char **argv, 
                      void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), 
                      void *stack_end) { main(argc, argv, NULL); }
void __halt(void) { while (1); }

// Global data
char aU[304] = "_______________________________\n|_U_    |    ___|___    |    ___|\n|    ___    |       |   ____    |\n|___|   |_______|___________|   |\n|           |       |   ________|\n#.####..##.#.##.....#.##...####..\n..###.#.####.#..#.#.#..#.. .###.#\n.#.###.#.#.#..#.#.....##.#.....#.\n...##...###.#..##..###.#.#######\n";
char byte_4010 = 0;
void *off_4008 = &off_4008;

// Placeholder for maze data (assumed)
uint32_t unk_21E0[256] = {0};

// Initialization stub
__int64 (**init_proc())(void) {
    return NULL;
}

// Start function (fixed)
void start(__int64 a1, __int64 a2, void (*a3)(void)) {
    __int64 stack_end = 0;
    char *argv[2] = {NULL, NULL};
    _libc_start_main(main, a2, argv, NULL, NULL, a3, &stack_end);
    __halt(); // Ensure it doesn't return
}

// RC4-like encryption function (fixed to use pointers)
unsigned __int64 sub_11E9(uint8_t *input, size_t input_len, uint8_t *key, size_t key_len, uint8_t *output) {
    uint8_t v16[512];
    int i, j, v12, v13, v14;
    size_t k;

    for (i = 0; i <= 255; ++i) {
        v16[i + 256] = i;
        v16[i] = key[i % key_len];
    }
    v13 = 0;
    for (j = 0; j <= 255; ++j) {
        v13 = (v13 + v16[j + 256] + v16[j]) % 256;
        uint8_t temp = v16[j + 256];
        v16[j + 256] = v16[v13 + 256];
        v16[v13 + 256] = temp;
    }
    v12 = 0;
    v14 = 0;
    for (k = 0; k < input_len; ++k) {
        v12 = (v12 + 1) % 256;
        v14 = (v14 + v16[v12 + 256]) % 256;
        uint8_t temp = v16[v12 + 256];
        v16[v12 + 256] = v16[v14 + 256];
        v16[v14 + 256] = temp;
        output[k] = input[k] ^ v16[(v16[v12 + 256] + v16[v14 + 256]) % 256 + 256];
    }
    return 0; // No stack canary check needed
}

// Main function
int main(int argc, char **argv, char **envp) {
    size_t v4, v5;
    char v6;
    int v7 = 0, i, j, v10, v12;
    uint32_t v13[256];
    uint8_t v14[8] = {0x06, 0x64, 0x70, 0xA5, 0x36, 0x27, 0x48, 0xE8};
    uint8_t v19[48] = {0};
    char s[104];

    memcpy(v13, unk_21E0, sizeof(v13));
    for (i = 0; aU[i]; ++i)
        putchar(aU[i]);
    printf("\nEnter the moves [a/w/s/d]: ");
    scanf("%103s", s);

    if (strlen(s) == 39) {
        for (j = 0; j < strlen(s); ++j) {
            v6 = s[j];
            v12 = 4 * v7;
            v10 = 0;
            if (v6 == 'd' && v13[v12 + 3] == 1 && v7 % 8 != 7) {
                ++v7;
                v10 = 1;
            } else if (v6 == 'a' && v13[v12] == 1 && (v7 & 7) != 0) {
                --v7;
                v10 = 1;
            } else if (v6 == 's' && v13[v12 + 2] == 1 && v7 <= 55) {
                v7 += 8;
                v10 = 1;
            } else if (v6 == 'w' && v13[v12 + 1] == 1 && v7 > 7) {
                v7 -= 8;
                v10 = 1;
            }
            if (!v10) {
                puts("you've reached a dead end");
                return 1;
            }
        }
        if (v7 == 40) {
            v4 = strlen(s);
            v5 = sizeof(v14); // Use actual size of v14
            sub_11E9(v14, v5, (uint8_t *)s, v4, v19);
            printf("You're out, here's your flag: ");
            for (i = 0; i < v5; ++i)
                putchar((unsigned char)v19[i]);
            putchar('\n');
        } else {
            puts("you've come the wrong way...");
        }
        return 0;
    } else {
        puts("you're not there yet");
        return 1;
    }
}

// Termination stub
void term_proc() {}